services:
  # Apache + PHP サービス
  app:
    build:
      context: ./docker/app/
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html/src
    volumes:
      - ./:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db

  # MySQL サービス
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  # phpMyAdmin サービス
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
      UPLOAD_LIMIT: 300M
    ports:
      - "8081:80"
    depends_on:
      - db

  # Node.js (Vue.js開発用)
  node:
    image: node:22-alpine
    container_name: laravel_node
    working_dir: /var/www/html/src
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
      - "3000:3000"
    command: tail -f /dev/null  # コンテナを起動したままにする

volumes:
  mysql_data:
    driver: local